# Configuration for running Rose test battery on Travis CI
# See https://travis-ci.org/ for more info.

---
language: python
python:
    - 2.7

stages:
    - test
    - report

before_install:
    - wget 'https://github.com/cylc/cylc/archive/master.tar.gz' -O '/tmp/cylc-master.tar.gz'
    - tar -xvf '/tmp/cylc-master.tar.gz' -C "${HOME}"
    - make -C "${HOME}/cylc-master" 'version'
    - wget 'https://github.com/metomi/fcm/archive/master.tar.gz' -O '/tmp/fcm-master.tar.gz'
    - tar -xvf '/tmp/fcm-master.tar.gz' -C "${HOME}"
    - cat >"${HOME}/.bashrc" <<<"export PATH=${PWD}/bin:${HOME}/fcm-master/bin:${HOME}/cylc-master/bin:\$PATH"
    - source "${HOME}/.bashrc"
    - ssh-keygen -t 'rsa' -f "${HOME}/.ssh/id_rsa" -N '' -q
    - cat "${HOME}/.ssh/id_rsa.pub" >>"${HOME}/.ssh/authorized_keys"
    - ssh-keyscan -t 'rsa' 'localhost' >>"${HOME}/.ssh/known_hosts"
    # Coverage dependencies
    - pip install coverage pytest-cov
    - sudo apt-get install -y jq libxml-xpath-perl
    - latestcodacyjar=$(curl "https://oss.sonatype.org/service/local/repositories/releases/content/com/codacy/codacy-coverage-reporter/maven-metadata.xml" | xpath -e "/metadata/versioning/release/text()")
    - echo "Downloading latest version $latest of codacy reporter from sonatype"
    - mvn dependency:get dependency:copy -DoutputDirectory=$HOME -DoutputAbsoluteArtifactFilename=true -Dmdep.stripVersion=true -DrepoUrl=https://oss.sonatype.org/service/local/repositories/releases/content/ -Dartifact=com.codacy:codacy-coverage-reporter:$latestcodacyjar:jar:assembly


install: 
    - >
        sudo apt-get install -y at build-essential gfortran heirloom-mailx
        pcregrep python-pip python-dev graphviz libgraphviz-dev python-jinja2
        python-sqlalchemy libxml-parser-perl libconfig-inifiles-perl
        libdbi-perl libdbd-sqlite3-perl latexmk texlive
        texlive-generic-extra texlive-latex-extra texlive-fonts-recommended
    - pip install cherrypy EmPy Jinja2 requests sqlalchemy pyopenssl pycodestyle
    - pip install pygraphviz --install-option="--include-path=/usr/include/graphviz" --install-option="--library-path=/usr/lib/graphviz/"
    - sudo sh -c 'echo "deb http://opensource.wandisco.com/ubuntu `lsb_release -cs` svn19" >> /etc/apt/sources.list.d/subversion19.list'
    - sudo wget -q http://opensource.wandisco.com/wandisco-debian.gpg -O- | sudo apt-key add -
    - sudo apt-get update
    - sudo apt-get install -y subversion


jobs:
    include:
        # Run tests
        - stage: test
          script:
          - export COVERAGE_PROCESS_START="${TRAVIS_BUILD_DIR}/.coveragerc"
          - export PYTHONPATH="${TRAVIS_BUILD_DIR}/.travis"
          - coverage run .travis/cover.py
          - unset PYTHONPATH
          - rose make-docs --venv --dev --strict clean linkcheck doctest html slides latexpdf
          after_script:
          - coverage combine --append
          - coverage xml --ignore-errors
          - java -jar ~/codacy-coverage-reporter-assembly.jar report -l Python -r ${TRAVIS_BUILD_DIR}/coverage.xml --partial

        # Report metrics, such as coverage
        - stage: report
          script: java -jar ~/codacy-coverage-reporter-assembly.jar final
